#ifndef __DEFAULT_CONSTANTS_H__
#define __DEFAULT_CONSTANTS_H__

/* TIME SAMPLINGS */
#define DEFAULT_SAMP_MOTOR_US 5173
#define DEFAULT_SAMP_PID_MOTOR_US 4173
#define DEFAULT_SAMP_MOTOR_ENCODER_US 20000

#define DEFAULT_SAMP_IK_US 15000
#define DEFAULT_SAMP_UPD_POS_US 12000
#define DEFAULT_SAMP_ODOMETRY_US 12731

#define DEFAULT_SAMP_STICK_US 13000
#define DEFAULT_SAMP_STICK_MS 13

/* WAIT TIME */
#define DEFAULT_MOTOR_WAIT_TIME_MS 10
#define DEFAULT_PNEUMATIC_WAIT_TIME_MS 300

#endif // __DEFAULT_CONSTANTS_H__
