#ifndef _STATE_H_
#define _STATE_H_

// Reloader
#define STATE_RELOADER_GOING_DOWN '1'
#define STATE_RELOADER_GOING_STANDBY_POSITION '2' // STANDBY FOR SHOOT
#define STATE_RELOADER_DOWN '3'
#define STATE_RELOADER_STANDBY_POSITION '4'
#define STATE_RELOADER_HALTING '5'
#define STATE_RELOADER_SHAKE_UP '6'
#define STATE_RELOADER_SHAKE_MIDDLE '7'
#define STATE_RELOADER_SHAKE_DOWN '8'

// Shooter
#define STATE_SHOOTER_READY '0'
#define STATE_SHOOTER_NOT_READY '1'
#define STATE_SHOOTER_AIM_UP '2'
#define STATE_SHOOTER_AIM_DOWN '3'
#define STATE_SHOOTER_SHOOT '4'

#endif